{% set version = "1.3.0" %}

package:
  name: requests-cache
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/r/requests-cache/requests_cache-{{ version }}.tar.gz
  sha256: 070e357ccef11a300ccef4294a85de1ab265833c5d9c9538b26cd7ba4085d54a

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - hatchling

  run:
    - python >={{ python_min }}
    - attrs >=21.2
    - cattrs >=22.2
    - itsdangerous >=2.0
    - platformdirs >=2.5
    - pyyaml >=6.0.1
    - requests >=2.22
    - ujson >=5.4
    - url-normalize >=1.4
    - urllib3 >=1.25.5

test:
  requires:
    - pip
    - python {{ python_min }}
  commands:
    - pip check
  imports:
    - requests_cache
    - requests_cache.backends
    - requests_cache.models
    - requests_cache.policy
    - requests_cache.serializers

about:
  home: https://github.com/requests-cache/requests-cache
  license_file: LICENSE
  license: BSD-2-Clause
  license_family: BSD
  summary: A persistent HTTP cache for python requests 
  doc_url: https://requests-cache.readthedocs.io

extra:
  recipe-maintainers:
    - jwcook
    - cj-wright
